# HANDOFF — {{PROJECT_NAME}}

> Phase 7 artifact. Hand-runnable by a second engineer. Generated by `bequite handoff`.

## TL;DR for engineers

**What it is:** {{PROJECT_DESCRIPTION}}

### How to run it locally

```bash
git clone {{REPO_URL}}
cd {{PROJECT_SLUG}}
{{INSTALL_COMMAND}}
{{BOOT_COMMAND}}
```

### How to deploy

{{DEPLOY_COMMANDS}}

### Where the moving parts live

{{PROJECT_FILE_TREE}}

### Adding a feature (as a second engineer)

```bash
bequite discover "<feature description>"
bequite plan
bequite implement <task-id>
bequite verify
bequite review
git push origin <feature-branch>
# CI runs the same `bequite verify` gates
```

### Recovery (if something breaks)

1. Identify failing command + read its stderr.
2. Check `state/recovery.md` for the last green checkpoint.
3. Run `bequite audit` to see Constitution / Doctrine drift.
4. Run `bequite verify` to identify which gate is red.
5. Fix the smallest unit; re-run.

## TL;DR for non-engineers ("vibe-handoff")

{{NON_ENGINEER_SUMMARY}}

### What you can do

- {{USER_ACTION_1}}
- {{USER_ACTION_2}}
- {{USER_ACTION_3}}

### What you cannot do (yet)

- {{NON_GOAL_1}}
- {{NON_GOAL_2}}

### Operating cost (estimate)

{{COST_TABLE}}

## Risk register

| Risk | Likelihood | Mitigation |
|---|---|---|
{{RISKS_ROWS}}

## Skeptic kill-shot

> "If I hand this to a different engineer who's never seen this project, can they boot locally + ship a feature in their first week?"

{{KILL_SHOT_ANSWER}}

## Cross-references

- Stack ADR: `.bequite/memory/decisions/ADR-001-stack.md`
- Spec: `specs/<feature>/spec.md`
- Phases: `specs/<feature>/phases.md`
- Tasks: `specs/<feature>/tasks.md`
- Doctrines: `.bequite/doctrines/`
- Constitution: `.bequite/memory/constitution.md`
- Receipts: `.bequite/receipts/`
