#!/usr/bin/env bash
# template/scripts/self-walk.sh — boots the app, exercises every route as
# admin + user, captures console errors + 4xx/5xx, dumps a verdict.
#
# Generated by `bequite init`. Adjust per project specifics. Used by
# `bequite verify` (Phase 6) as the second-line check after Playwright walks.
#
# Article II — verification before completion. Output saved to
# evidence/P6/self-walk-<timestamp>.log

set -euo pipefail

BASE_URL="${BASE_URL:-http://localhost:3000}"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H-%M-%SZ")
LOG_DIR="evidence/P6"
LOG="$LOG_DIR/self-walk-${TIMESTAMP}.log"

mkdir -p "$LOG_DIR"

echo "[self-walk] base_url=$BASE_URL timestamp=$TIMESTAMP" | tee "$LOG"

# 1. Confirm the app responds.
echo "[self-walk] step 1: probe root..." | tee -a "$LOG"
ROOT_STATUS=$(curl -s -o /dev/null -w '%{http_code}' "$BASE_URL/" || echo '000')
echo "[self-walk]   GET / → $ROOT_STATUS" | tee -a "$LOG"
if [[ "$ROOT_STATUS" != "200" && "$ROOT_STATUS" != "301" && "$ROOT_STATUS" != "302" ]]; then
  echo "[self-walk] FAIL — root returned $ROOT_STATUS; app not booted?" | tee -a "$LOG"
  exit 1
fi

# 2. Walk every public route declared in routes.json (or the project's equivalent).
ROUTES_FILE="${ROUTES_FILE:-tests/routes.json}"
if [[ ! -f "$ROUTES_FILE" ]]; then
  echo "[self-walk] WARN — no routes.json at $ROUTES_FILE; falling back to common routes" | tee -a "$LOG"
  ROUTES=("/" "/sign-in" "/sign-up" "/about" "/api/health")
else
  # Parse routes.json (one URL per line).
  mapfile -t ROUTES < <(jq -r '.[]' "$ROUTES_FILE" 2>/dev/null || cat "$ROUTES_FILE")
fi

ANY_FAILED=0
for route in "${ROUTES[@]}"; do
  STATUS=$(curl -s -o /dev/null -w '%{http_code}' "$BASE_URL$route" || echo '000')
  echo "[self-walk]   GET $route → $STATUS" | tee -a "$LOG"
  case "$STATUS" in
    2[0-9][0-9]|3[0-9][0-9]|401|403)
      # Acceptable: success / redirect / auth-required.
      ;;
    *)
      ANY_FAILED=1
      echo "[self-walk]   FAIL on $route ($STATUS)" | tee -a "$LOG"
      ;;
  esac
done

# 3. (Optional) Sign in as admin + user via the admin/user walks.
# The full role-based walk lives in Playwright (tests/e2e/<role>/); this
# script does the cheap-curl sweep before kicking the heavier suite.

# 4. Verdict.
if (( ANY_FAILED == 0 )); then
  echo "[self-walk] PASS — every route returned 2xx/3xx/401/403" | tee -a "$LOG"
  exit 0
else
  echo "[self-walk] FAIL — at least one route returned an unexpected status" | tee -a "$LOG"
  exit 1
fi
