# axe-core accessibility gate — template (Doctrine `default-web-saas` Rule 8)
#
# Lands at `.github/workflows/axe.yml` in projects loaded with a frontend Doctrine.
# Generated by `bequite init` when frontend Doctrine active.
#
# Behavior:
# - Runs on every PR + every push to main + nightly.
# - Boots the app + traverses the sitemap as authenticated admin AND user.
# - Runs axe-core on each page; fails the build on any violation at WCAG AA.
# - Captures HTML report + JSON for evidence trail.
#
# Cross-reference:
# - skill/templates/playwright.config.ts.tpl — ship with axe-playwright wired in.
# - skill/skills-bundled/impeccable/references/anti-patterns.md item #9.
# - cli/bequite/verify.py — runs the axe gate per-Mode.

name: axe-core a11y gate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # 03:00 UTC nightly to catch dependency-driven regressions
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  axe:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      NODE_ENV: test
      CI: true
      BASE_URL: http://localhost:3000
      TEST_ADMIN_EMAIL: ${{ "{{" }} secrets.TEST_ADMIN_EMAIL {{ "}}" }}
      TEST_ADMIN_PASSWORD: ${{ "{{" }} secrets.TEST_ADMIN_PASSWORD {{ "}}" }}
      TEST_USER_EMAIL: ${{ "{{" }} secrets.TEST_USER_EMAIL {{ "}}" }}
      TEST_USER_PASSWORD: ${{ "{{" }} secrets.TEST_USER_PASSWORD {{ "}}" }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "{{PACKAGE_MANAGER}}"  # npm | pnpm | yarn | bun

      - name: Install dependencies
        run: {{INSTALL_CMD}}            # e.g. pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Build
        run: {{BUILD_CMD}}              # e.g. pnpm build

      - name: Start app
        run: {{START_CMD}} &            # e.g. pnpm start &
        env:
          PORT: 3000

      - name: Wait for app
        run: npx wait-on http://localhost:3000 -t 60000

      - name: Run axe via Playwright walks
        run: npx playwright test --project=axe-admin --project=axe-user

      - name: Upload axe reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: axe-reports-${{ "{{" }} github.run_id {{ "}}" }}
          path: |
            evidence/P6/axe/
            playwright-report/
            test-results/
          retention-days: 30

      - name: Fail on violations
        if: failure()
        run: |
          echo "::error::axe-core gate failed. See artifacts for HTML + JSON reports."
          exit 1

  axe-summary:
    needs: axe
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Comment on PR
        if: github.event_name == 'pull_request' && needs.axe.result == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ **axe-core a11y gate failed.**\n\nCheck the workflow artifacts for the HTML report. Doctrine `default-web-saas` Rule 8: zero violations is required for merge.\n\nTo reproduce locally: `npx playwright test --project=axe-admin --project=axe-user`'
            })
