# bequite.config.toml — per-project BeQuite configuration
#
# Generated by `bequite init`. Edit to override defaults.
# This file is read by every BeQuite skill / CLI invocation.
#
# Do NOT commit secrets here. Reference env vars instead.

[project]
name = "{{PROJECT_NAME}}"
slug = "{{PROJECT_SLUG}}"
owner = "{{PROJECT_OWNER}}"
maintainer = "{{MAINTAINER_EMAIL}}"
license = "{{LICENSE}}"                          # MIT | Apache-2.0 | BSD-3-Clause | proprietary
constitution_version = "1.0.1"

# Mode (master §4) — drives gating rigour for THIS project.
# fast | safe | enterprise
mode = "{{MODE}}"

# Audience flag — informs artefact polish.
# engineer | vibe-handoff
audience = "{{AUDIENCE}}"

# Active Doctrines — order matters; on conflict, earlier wins.
# Available shipped Doctrines:
#   default-web-saas, cli-tool, ml-pipeline, desktop-tauri, library-package,
#   mena-bilingual, fintech-pci, healthcare-hipaa, gov-fedramp
# Or list a fork at .bequite/doctrines/<your-name>.md
doctrines = [{{ACTIVE_DOCTRINES}}]

# Scale tier (master §5 + Article V binding) — declared ceiling.
# Implementation MUST NOT cap below this. Bumping requires an ADR.
# Values: solo | small_saas | mid_market | country | hyperscale | library_tool
scale_tier = "{{SCALE_TIER}}"

# Compliance overlays — drives Doctrine + persona behaviour.
# none | pci_dss_v4_0 | hipaa | fedramp_low | fedramp_moderate | fedramp_high | gdpr | soc2 | iso27001
compliance = [{{COMPLIANCE}}]

# Locales — drives i18n + RTL behaviour.
# Examples: ["en-US"] | ["en-US", "ar-EG"] (mena-bilingual triggers RTL)
locales = [{{LOCALES}}]


[safety_rails]
# Auto-mode session limits.
cost_ceiling_usd = 20
wall_clock_ceiling_hours = 6
consecutive_failure_threshold = 3
heartbeat_minutes = 5

# Banned phrases in completion messages (Iron Law II).
# stop-verify-before-done.sh exits 2 if any of these appear.
banned_completion_phrases = [
    "should",
    "probably",
    "seems to",
    "appears to",
    "I think it works",
    "might work",
    "hopefully",
    "in theory",
]

# Auto-mode pause triggers — non-overridable.
pause_on = [
    "cost_ceiling_reached",
    "wall_clock_ceiling_reached",
    "three_consecutive_failures",
    "banned_phrase_detected",
    "hook_block",                  # PreToolUse exit 2 — never auto-override
    "stack_adr_sign_off",          # one-way door
    "first_handoff_generation",    # human review required
    "tier_3_command",              # delete database, force-push, rotate secrets, etc.
    "publish_to_pypi",
    "publish_to_npm",
    "git_push_to_main",
    "git_push_force",
    "terraform_apply",
    "shared_db_migration",
]


[routing]
# Override skill/routing.json defaults here. See that file for keys.
# Empty by default; edit when needed.
#
# Example:
#   [[routing.overrides]]
#   phase = "P5"
#   persona = "backend-engineer"
#   model = "claude-haiku-4-5"
#   reasoning_effort = "medium"
#   note = "This project's backend is straightforward CRUD; cheaper model fine."


[providers]
# API keys via env vars only. Never hardcode.
anthropic = { api_key_env = "ANTHROPIC_API_KEY" }
openai = { api_key_env = "OPENAI_API_KEY" }
google = { api_key_env = "GOOGLE_API_KEY" }
deepseek = { api_key_env = "DEEPSEEK_API_KEY" }


[freshness]
# bequite freshness probe (v0.4.3+).
cache_ttl_hours = 24
check_pricing_pages = true
check_osv = true
check_github_last_commit = true
github_last_commit_max_age_months = 6
fail_stack_adr_on_stale = true


[receipts]
# Reproducibility receipts (v0.7.0 → v0.7.1+).
emit_per_phase = true
sign_with_ed25519 = true                # v0.7.1+
chain_parent_hash = true
storage_dir = ".bequite/receipts"


[evidence]
# Filesystem evidence (master §3.6, §10.3, §21).
storage_dir = "evidence"
require_screenshot_for_ui = true        # frontend Doctrines
require_test_output_for_implement = true
require_lint_output_for_implement = true
require_typecheck_output_for_implement = true


[memory]
# Memory Bank (Cline pattern) lives at .bequite/memory/.
# state/ files are operational (lighter; refresh more often).
# Both required.
memory_bank_dir = ".bequite/memory"
state_dir = "state"
prompts_dir = "prompts"


[hosts]
# Per-host adapters (v0.12.0). Generated by `bequite skill install <host>`.
# claude_code | cursor | codex | gemini | windsurf | cline | kilo | continue | aider
primary_host = "{{PRIMARY_HOST}}"
generate_adapters_for = [{{HOST_LIST}}]


[skills]
# Bundled peer skills (vendored, pinned).
# Loaded automatically when their associated Doctrine is active.
[skills.impeccable]
path = "skill/skills-bundled/impeccable"
loaded_when_doctrine = ["default-web-saas", "mena-bilingual"]
attribution = "Paul Bakaus (pbakaus/impeccable, MIT)"


[telemetry]
# Off by default. Opt-in only (per ADR-002 — pending v0.7.0).
# Receipts are local-only; no network egress for cost / usage tracking unless explicitly enabled.
enabled = false
mode = "off"                            # off | receipts_only | full
endpoint = ""                           # only used when mode != off


[mena_bilingual]
# Active only when mena-bilingual Doctrine is loaded (v0.11.0+).
# Researcher persona scrapes these channels for product feedback.
# Owner seeds the list before v0.11.0 work begins.
twitter_x_seeds = [
    # "@..."
]
telegram_seeds = [
    # "@..."
]
# Egyptian Arabic dialect support
default_dialect = "ar-EG"
rtl_default = true
font_stack_override = ["Tajawal", "Cairo", "Readex Pro"]


[# Notes]
# - `state/project.yaml` is the AUTHORITATIVE current state.
# - This file is the static configuration; values can be lifted into project.yaml at init.
# - Changes to `mode` mid-project require an ADR.
# - Changes to `compliance` mid-project require an ADR + security-reviewer signoff.
