/**
 * playwright.config.ts — Playwright configuration for BeQuite Phase 6 verification.
 *
 * Generated by `bequite init`. Edit per project specifics; the structure
 * follows the qa-engineer persona's planner → spec writer → generator →
 * healer pattern.
 */

import { defineConfig, devices } from '@playwright/test';

const BASE_URL = process.env.BASE_URL ?? 'http://localhost:3000';
const IS_CI = !!process.env.CI;

// Locales declared by the project (mena-bilingual Doctrine adds ar-EG).
const LOCALES = ({{LOCALES_JSON}} as readonly string[]) ?? ['en-US'];

// Viewports walked per the qa-engineer + default-web-saas Doctrine Rule 7.
const VIEWPORTS = [
  { name: 'mobile-360',   viewport: { width: 360,  height: 800  } },
  { name: 'desktop-1440', viewport: { width: 1440, height: 900  } },
];

// Roles declared in tests/walkthroughs/<role>-walk.md.
const ROLES = ['admin', 'user'] as const;

// Build a project per role × viewport × locale combination.
const projects = ROLES.flatMap((role) =>
  VIEWPORTS.flatMap((vp) =>
    LOCALES.map((locale) => ({
      name: `${role}-${vp.name}-${locale}`,
      testDir: `./tests/e2e/${role}`,
      use: {
        ...devices['Desktop Chrome'],
        baseURL: BASE_URL,
        viewport: vp.viewport,
        locale,
        // RTL when locale is Arabic-family (mena-bilingual Doctrine).
        ...(locale.startsWith('ar') ? { extraHTTPHeaders: { 'Accept-Language': locale }, colorScheme: 'light' } : {}),
        trace: IS_CI ? 'on-first-retry' : 'retain-on-failure',
        screenshot: 'only-on-failure',
        video: 'retain-on-failure',
      },
      dependencies: ['setup'],
    }))
  )
);

// axe-core a11y projects (Doctrine `default-web-saas` Rule 8) — one per role.
// Walks the same routes as functional walks; runs axe-core after each navigation;
// fails on any WCAG AA violation. Reports merged into evidence/P6/axe/.
const axeProjects = ROLES.map((role) => ({
  name: `axe-${role}`,
  testDir: `./tests/a11y/${role}`,
  use: {
    ...devices['Desktop Chrome'],
    baseURL: BASE_URL,
    viewport: { width: 1440, height: 900 },
    locale: LOCALES[0] ?? 'en-US',
    trace: IS_CI ? 'on-first-retry' : 'retain-on-failure',
    screenshot: 'only-on-failure',
    video: 'off',
  },
  dependencies: ['setup'],
}));

export default defineConfig({
  testDir: './tests',
  // Setup project runs tests/seed.spec.ts BEFORE all e2e walks.
  projects: [
    {
      name: 'setup',
      testMatch: /.*\bseed\.spec\.ts/,
    },
    ...projects,
    ...axeProjects,
  ],
  fullyParallel: !IS_CI,           // serial in CI to avoid DB contention
  forbidOnly: IS_CI,               // CI fails on .only()
  retries: IS_CI ? 2 : 0,
  workers: IS_CI ? 1 : undefined,  // single worker in CI for determinism
  timeout: 30_000,
  expect: { timeout: 5_000 },

  // Global setup / teardown (DB reset + cleanup).
  globalSetup: process.env.GLOBAL_SETUP_FILE,
  globalTeardown: process.env.GLOBAL_TEARDOWN_FILE,

  // Reporters: HTML + JUnit (CI) + bequite-receipt (the qa-engineer's healer reads this).
  reporter: IS_CI
    ? [
        ['junit', { outputFile: 'evidence/P6/playwright-junit.xml' }],
        ['html',  { outputFolder: 'evidence/P6/playwright-html' }],
        ['json',  { outputFile: 'evidence/P6/playwright-results.json' }],
      ]
    : [['html', { open: 'on-failure' }]],

  // Output directory for traces, screenshots, videos.
  outputDir: 'evidence/P6/playwright-output',

  // Web server: started before the suite runs (when not already running).
  webServer: process.env.SKIP_WEB_SERVER
    ? undefined
    : {
        command: '{{WEB_SERVER_COMMAND}}',           // e.g. `pnpm dev` / `pnpm start`
        url: BASE_URL,
        reuseExistingServer: !IS_CI,
        timeout: 120_000,
      },
});
